### ISSUE TITLE
combined query not paginating with `useQueryWithPagination`

### ISSUE THREAD

**Issue by hexcowboy** [Airstack-xyz/airstack-web-sdk#3] opened 2023-05-20 23:57 UTC
I have a combined query:

```ts
export const getNFTCollectionQuery = `query GetNFTCollection($contractAddress: Address!, $blockchain: TokenBlockchain!) {
  Tokens(
    input: {filter: {address: {_eq: $contractAddress}}, blockchain: $blockchain}
  ) {
    Token {
      projectDetails {
        collectionName
        description
      }
    }
  }
  TokenNfts(
    input: {filter: {address: {_eq: $contractAddress}}, blockchain: $blockchain, order: {tokenId: ASC}, limit: 12}
  ) {
    TokenNft {
      address
      chainId
      tokenId
      blockchain
      contentValue {
        image {
          medium
        }
        animation_url {
          original
        }
      }
    }
    pageInfo {
      nextCursor
      prevCursor
    }
  }
}`;
```

However, when I use the `useQueryWithPagination` hook it seems like the `pagination.hasNextPage` is always false.

```ts
  let queryArgs: [string, Record<string, any>] = [
    getNFTCollectionQuery,
    { contractAddress: address, blockchain: "ethereum" },
  ];

  const { data, loading, pagination } = useQueryWithPagination(...queryArgs);
  const { hasNextPage, getNextPage } = pagination;
  console.log(hasNextPage); // false
```

**Comment by YosephKS** [comment] 2023-08-04 08:56
Hey @hexcowboy,

Thanks for raising an issue here and so sorry for the late reply.

We have just checked on your code and looks like we cannot replicate the issue that you are having.

It could be that we might have fixed the issue some time after your reporting, so please test it out again and see whether or not the issue is fixed on your end by updating your SDK to the latest version.

Let me know if you still have the issue on your end, we can investigate further on it~

**Closed by YosephKS** 2023-08-04 08:56 UTC
